name: my_fatoorah
description: My Fatoorah Payment SDK Integration works for android and ios
version: 3.0.11
homepage: https://github.com/mo-ah-dawood/my_fatoorah

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_inappwebview: ^5.4.2

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
