name: my_fatoorah
description: My Fatoorah Payment SDK Integration works for android and ios
version: 3.3.0
homepage: https://github.com/mo-ah-dawood/my_fatoorah

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  #flutter_inappwebview: 5.7.2+3
  flutter_inappwebview:
    git:
      url: https://github.com/MobileEasternts/flutter_inappwebview.git
      path: flutter_inappwebview
dev_dependencies:
  lints: ^2.1.0
  flutter_test:
    sdk: flutter

